version: 2.1

jobs:
  build-image:
    parameters:
      image-name:
        description: The name of the base image being built. Should be a directory at the root of the repository.
        type: string

    docker:
      - image: ubuntu:18.04

    steps:
      - run:
          name: Install essential packages
          command: |
            apt-get update
            apt-get install -y ca-certificates curl git openssh-client gnupg software-properties-common

      - checkout

      - run:
          name: Install Docker client
          command: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            apt-key fingerprint 0EBFCD88
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
            apt-get update
            apt-get install -y docker-ce=18.03.1~ce~3-0~ubuntu

      - setup_remote_docker:
          version: 18.03.1-ce

      - run:
          name: Build
          command: docker build -t mozilla/ci-base-<< image-name >> << image-name >>/

  deploy-image:
    parameters:
      image-name:
        description: The name of the base image being built. Should be a directory at the root of the repository.
        type: string

    docker:
      - image: ubuntu:18.04

    steps:
      - run:
          name: Dummy Deploy
          command: echo TODO implement deployment of << image-name >>

workflows:
  version: 2

  build_deploy:
    jobs:
      - build-image:
        name: build-docker
        image-name: docker

      - deploy-image:
          requires:
            - build-docker
          filters:
            branches:
              only: master