version: 2.1

jobs:
  build-and-deploy-image:
    description: Build and tag one of the base images in this repository.

    parameters:
      imageName:
        description: The name of the base image being built.
        type: string

    docker:
      - image: mozilla/cidockerbases:docker-2018-08-28

    steps:
      - checkout
      - run:
          name: Build
          command: docker build -t << parameters.imageName >> << parameters.imageName >>/

      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./bin/push-image.sh << parameters.imageName >>
            fi

workflows:
  version: 2

  build_deploy:
    jobs:
      - build-and-deploy-image:
          name: docker-build-and-deploy
          imageName: docker

      - build-and-deploy-image:
          name: firefox-build-and-deploy
          imageName: firefox
